name: Print Message

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [print-message]

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print the message
        run: echo "${{ github.event.client_payload.message }}"