name: My Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'The message to print'     
        required: true
        default: 'Hello, World!'

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print the message
        run: echo "${{ github.event.inputs.message }}"